vips: use existing mosaicing prototypes
Fix parsecmgmt -a build -p all with GCC 15.2.0-4ubuntu4 on Ubuntu 25.10.

It failed because find_mosaic redeclared existing mosaicing functions with empty parameter lists:

    find_mosaic.c:72:12: error: conflicting types for 'im_lrmerge'; have 'int(void)'
    mosaicing.h:40:5: note: previous declaration of 'im_lrmerge' with type 'int(IMAGE *, IMAGE *, IMAGE *, int, int, int)'
    find_mosaic.c:268:30: error: too many arguments to function 'im__find_lroverlap'; expected 0, have 16

Build command:
    parsecmgmt -a build -p all

Generated by Codex 5.4.