libxml2: prototype weak pthread declarations
Fix parsecmgmt -a build -p all with GCC 15.2.0-4ubuntu4 on Ubuntu 25.10.

It failed because old empty-parameter weak pthread declarations conflicted with the POSIX pthread prototypes:

    threads.c:66:12: error: conflicting types for 'pthread_mutex_init'; have 'int(void)'
    /usr/include/pthread.h:781:12: note: previous declaration of 'pthread_mutex_init' with type 'int(pthread_mutex_t *, const pthread_mutexattr_t *)'

Build command:
    parsecmgmt -a build -p all

Generated by Codex 5.4.