uptcpip: include byte order declarations
Fix parsecmgmt -a build -p all with GCC 15.2.0-4ubuntu4 on Ubuntu 25.10.

It failed because the host support code used network byte-order helpers without their declarations:

    host_serv.c:371:24: error: implicit declaration of function 'htons'
    host_serv.c:401:39: error: implicit declaration of function 'htonl'

Build command:
    parsecmgmt -a build -p all

Generated by Codex 5.4.