vips: prototype merge blend callbacks
Fix parsecmgmt -a build -p all with GCC 15.2.0-4ubuntu4 on Ubuntu 25.10.

It failed because merge blend callbacks were stored as empty-parameter functions:

    im_lrmerge.c:804:30: error: assignment to 'int (*)(void)' from incompatible pointer type
    im_lrmerge.c:956:29: error: too many arguments to function 'ovlap->blend'; expected 0, have 4
    merge.h:72:40: warning: 'struct _MergeInfo' declared inside parameter list will not be visible outside of this definition or declaration

Build command:
    parsecmgmt -a build -p all

Generated by Codex 5.4.