HUGE -> HUGE_VAL
Fixes error:

parsec-benchmark/pkgs/apps/ferret/obj/amd64-linux.gcc/src/lsh/LSH_query.c:200:38: error: ‘HUGE’ undeclared (first use in this function)
   if (query->topk[K - j - 2].dist >= HUGE) break;
                                      ^~~~

on Ubuntu 19.04 `parsecmgmt -a build -p all`.

This was present in Ubuntu 17.10 glibc, but not in 19.04. Not sure why
it was used in the first place, since not standard like HUGE_VAL
https://en.cppreference.com/w/cpp/numeric/math/HUGE_VAL