vips: prototype delayed save callbacks
Fix parsecmgmt -a build -p all with GCC 15.2.0-4ubuntu4 on Ubuntu 25.10.

It failed because delayed save callbacks were stored as empty-parameter functions:

    im_open.c:168:13: error: too many arguments to function 'sb->save_fn'; expected 0, have 2
    im_open.c:459:58: error: passing argument 2 of 'attach_sb' from incompatible pointer type

Build command:
    parsecmgmt -a build -p all

Generated by Codex 5.4.